Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(1,"Customer Srvc",1,1);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(2,"Finance", 1, 2);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(3, "Pharmacy", 1, 3);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(4, "Bakery", 1, 4);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(5, "Meat", 1, 3);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(6, "Seafood", 1, 2);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(7, "HR", 1, 2);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(8, "IT", 1, 3);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(9, "Accounting", 1, 3);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(10, "Security", 1, 1);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(11, "Marketing", 1, 2);
Insert INTO hrms.department(DID,D_name,D_mgrID,SID) values(12, "Pub.Relations", 1, 1);